services:
  media-cleaner:
    image: mikefosh/media-cleaner:main
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CST/UTC
      - SONARR_API_KEY=123456
      - RADARR_API_KEY=123456
      - QBIT_USER=admin
      - QBIT_PASS=password
      - SONARR_URL=http://sonarr:8989
      - RADARR_URL=http://radarr:7878
      - API_TIMEOUT=3600
    restart: unless-stopped 
    container_name: media-cleaner 
    hostname: media-cleaner 
    networks: 
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true 
      traefik.enable: true 
      traefik.http.routers.media-cleaner-http.entrypoints: web 
      traefik.http.routers.media-cleaner-http.middlewares: globalHeaders@file,redirect-to-https@docker,robotHeaders@file,cloudflarewarp@docker,authelia@docker 
      traefik.http.routers.media-cleaner-http.rule: Host(`cleaner.foshinbaur.com`) 
      traefik.http.routers.media-cleaner-http.service: media-cleaner 
      traefik.http.routers.media-cleaner.entrypoints: websecure 
      traefik.http.routers.media-cleaner.middlewares: globalHeaders@file,secureHeaders@file,robotHeaders@file,cloudflarewarp@docker,authelia@docker 
      traefik.http.routers.media-cleaner.rule: Host(`cleaner.foshinbaur.com`) 
      traefik.http.routers.media-cleaner.service: media-cleaner 
      traefik.http.routers.media-cleaner.tls.certresolver: cfdns 
      traefik.http.routers.media-cleaner.tls.options: securetls@file 
      traefik.http.services.media-cleaner.loadbalancer.server.port: 80 
    volumes: 
      - /opt/media-cleaner:/CONFIG
      - /etc/localtime:/etc/localtime:ro

networks: 
  saltbox:
    external: true
